### ISSUE TITLE
Is 1Forge data only for European companies?

### ISSUE THREAD

**Issue by juliohm** [1Forge/python-forex-quotes#1]
I don't see the symbol for AAPL for example. Could you please confirm?

Thank you,
-Júlio

**Comment by brutus-gr** [comment]
Hi,

It's only for Forex currency pairs.  If you're looking for stock data I recommend having a look at IEX https://iextrading.com/developer/docs/#stocks

**Comment by juliohm** [comment]
Thank you @jacobtylerdavis , I will take a look. Also, as a side note, the Python API does not work on Python 3.x at the moment.

Best,
-Júlio

**Comment by brutus-gr** [comment]
@juliohm thanks for letting me know, I will take a look.
