### ISSUE TITLE
Source code present only in tar.gz

### ISSUE THREAD

**Issue by rohitjha** [1Forge/python-forex-quotes#2]
I noticed that the files `python_forex_quotes/ForexDataClient.py` and `python_forex_quotes/__init__.py` are only present in `dist/python_forex_quotes-1.0.tar.gz`. Is it possible for you to make all the source code files available so that one need not download and extract them? Thank you.

**Comment by brutus-gr** [comment]
Hi @rohitjha 

Thanks for pointing this out.  I have moved the primary file `ForexDataClient.py` to the root directory of the repository.
